### ISSUE TITLE
naming of the module

### ISSUE THREAD

**Issue by nikolaipaul** [ghivert/elm-graphql#7]
The module name of this package is GraphQl however the official wording is "GraphQL". Maybe you should consider renaming it to the official form?

**Comment by ghivert** [comment]
Hi!

Well, that's an interesting question, but the goal to be named `GraphQl` is to be the closest possible to elm conventions. In official packages, when capital letters forms a word, like HTTP, the corresponding module is named `Http`. We can see the same thing for `Url`, which stands for URL.

So what should we choose for GraphQL, which contains capital letters? I'm personally for `GraphQl`, but if you have some arguments, I would be happy to hear them. 😄

**Comment by nikolaipaul** [comment]
Fair point. I don't really have an argument. My eye is probably just used to GraphQL and GraphQl looked awkward.

I quickly browsed through the package repo and could only find the webgl package, which is named WebGL instead of WebGl. It's not that it's something important.

**Comment by ghivert** [comment]
I think it's something important if it allows people to easily get into the package.

I still really don't know what to do, especially because changing names would mean doing a major upgrade versions, and I don't want to do it for such a thing. But this could be considered when making a major upgrade.

I'll let the issue open and let people put 👍 on topic if they consider the change is worth it. I think I'll close it in a while if no one else participate.
